#!/bin/bash

NUM_CARDS=`lspci | grep NVIDIA | grep VGA | wc -l`
LOC=`dirname $(readlink -f $0)`

function enable_all_cards() {
    if [[ $NUM_CARDS -gt 1 ]] ; then
        for i in $(seq 2 $NUM_CARDS) ; do
            mkdir -p card_$i
            j=$((i-1))
            echo "24 $j" > card_$i/0xbtc.conf
            cp card_1/cosmic_input card_$i/
        done
    fi
}

function is_pid_running() {
    if [[ $# -lt 2 ]] ; then
        return 2
    fi

    CPID="$1"
    if [[ $CPID =~ ^-?[0-9]+$ ]] ; then
		comm=$(basename `ps -p $CPID -o command -h | cut -d\  -f2`)
		if [[ "$comm" == "$2" ]] ; then
			return 0
		fi
    fi
    return 1
}

function stop_miner_on_card() {
    CARD=$1
    PIDFILE="$LOC/card_$CARD/cosmic.pid"
    COSMIC_STOPPED=0

    if [[ ! -e $PIDFILE ]] ; then
        echo "Miner not running on card $1."
        return 0
    fi

    p=`cat $PIDFILE`
    is_pid_running $p cosmic_input
    if [[ $? -eq 0 ]] ; then
        echo "Stopping miner on card $1."
        kill -15 $p 
    fi
    return 1
}

function usage() {
    COMM=`basename $0`
    echo "usage: $COMM [card number]" 
}

enable_all_cards

if [[ $# -eq 0 ]] ; then
    # With no arguments, run on cosmic miner on all cards
    for i in $(seq 1 $NUM_CARDS) ; do
        stop_miner_on_card $i
    done
    # Do an emergency stop, just in case of bad behaviour
    killall -3 "cosmic_input cosmic-v3.4-linux" >/dev/null 2>&1
else
   # Ensure that first argument is an integer in the valid range
   if [[ ! $1 =~ ^-?[0-9]+$ ]] ; then
       usage
       exit
   fi

   # Ensure that first argument is less than or equal to number of cards
   if [[ "$1" -gt "$NUM_CARDS" || $1 -lt 1 ]] ; then
       usage
       exit
   fi
   stop_miner_on_card $1
fi
