#!/bin/bash

NUM_CARDS=`lspci | grep NVIDIA | grep VGA | wc -l`
LOC=`dirname $(readlink -f $0)`
TOKENS=(spring summer autumn winter)

function usage() {
    COMM=`basename $0`
    if [[ $NUM_CARDS -lt 2 ]] ; then
        echo "usage: $COMM [spring|summer|autumn|winter]" 
    else
        echo "usage: $COMM [card number] [spring|summer|autumn|winter]" 
    fi
}


if [[ "$1" == "-h" ]] ; then
    usage
    exit 1
fi


if [[ $# -eq 0 ]] ; then
    usage
    exit 1
else
    if [[ $NUM_CARDS -lt 2 ]] ; then
        if [[ ${TOKENS[*]} =~ (^|[[:space:]])$1($|[[:space:]]) ]]; then
            ./stop_cosmic
            ./run_cosmic $1
        else
            usage
            exit 1
        fi
    else
       if [[ $# -eq 1 ]] ; then
           ./stop_cosmic  
           for i in $(seq 1 $NUM_CARDS) ; do
               ./run_cosmic $i $1
           done
       else
           # If more than two cards and two args, first arg must be 
           # a valid card number
           if [[ ! $1 =~ ^-?[0-9]+$ ]] ; then
               usage
               exit 1
           fi
           if [[ "$1" -gt "$NUM_CARDS" || $1 -lt 1 ]] ; then
               usage
               exit
           fi
           # valid token only for second arg
           if [[ ! ${TOKENS[*]} =~ (^|[[:space:]])$2($|[[:space:]]) ]]; then
               usage
               exit
           fi
           ./stop_cosmic $1 
           ./run_cosmic $1 $2
       fi
   fi
fi

